language: elixir
dist: xenial
services:
  - docker
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
branches:
  only:
  - "/.*/"
before_install:
  - docker pull nats:linux
  - docker run -d -p 4222:4222 nats:linux
  - docker ps -a
  - mkdir -p /tmp/stacks
elixir:
  - '1.9'
otp_release: 22.0
before_script:
  - make docker-deps
env:
  global:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=postgres
  - secure: uQYh4+aNadz66uF486V7mzYD8N4psuYb4Eh2yVF++Htfpr5vBaPYJ01eS9AufzcELUrbvoiLmmW/J9JLQb1hqbqp1aYt91sIEywtpZh0J208g8ClCRBBvBMa3l22v8NpMZAwLexN7jAoxVDSI/Fg9ZqdR8udfZJ6G5dzVqQ/2kGQbTVGnC+sbuFopSu6i0u+W7wy12SCyIX60qlgjk+1imTjAQDLEQX9uS1xbW4XHUeh3KQhJ5Xbgcz/wfw4CedRXk75qYM955kboeu9CBmwWS/Z2LPhBRszuDvWgPes8nwU346M/4QHZPU4hyfODTN+PiPdDIPtNJgOSIHBTRqh8lbyisCczReoLlzqxtzs4Y3A5xV1eUgISNKI143QdkpAJibUrAK7jFEP5hrmkQqDwDS/djDFpeddMfS6z13Kc0lxZ5MhOPQu/b6YcL1r5nEtpfn1ShzV6Vi7ealkMEGDoUJsqKJzhHP5wg3IgBjJjAJTOnETqN6GWP06dxSx3a7K9SooMlPAAJOEzM6A/RB2D7V/Bs4nJLa1YX3tTjKVh7f0wdhEkzRMA+5oFylvKUOqZUzVFDkQSLgY+fEjmj+k+FU2I0k9P0xRqLf2cS0efTFwYUn5Q/DaM5eUlS4/tCdeGyPCJVWRNLiBOZYo9M+/32Vf7YAZV9p1nlk3TUk7kE8=
  - secure: qhGGUatWfWtwTN1N23wddIx5cy7CCkxp10na59o5al1uImg/yrPAtRhJhhqK+hSqP7shsezRV1SYm4R4kEllmqGr/EyCpoeBcS8ebnUP38HGOU1odCnh/bUk9Iuvo2jjpXTtHTu3ttd+IL6Q31aF5UD1p3opD6YdspvkK21T5FK2ZNSQLBWMLq1MyMb/wdXbgpTAIfWDkLC+Bw/peo9CBnsT5vOhAZfKsK4UMQqugSYK8TWGWKThUPhJk8IOtRCHt3Kvv6Cii/UH0gPDy6tG67Y9qbylBcjW9nAkbWFipmkxABmd/yi+i4xygw4WJl1YnAWE8f0wgy/s/xSmO6mdyko6dj6JkReUrFGb0RU5kc5tCqF7zO+j1oFRdRSywihfz4TRnybgvuqnZKV9DZDTRpZ0OjtI04p4KpKaVjSxvLPDf0Njz80IUMuGANzHp+zWW6kwT52hYITii389vauYICQ7ygzt0LWdwQqSE8Dus2FfWfOlrOadNTl+B+9nQHy0n6TVUF3G83Mxz3CuKHcW3d7Vlrd/SK/2w5ym6H4Xt90uHZCDggP9t7qYRqiQpHs7e70f4I9rJOUPIw8juAzKvbqPMc4HSMa4f03YMfMU8q/f5HSpV/jvgg6vq6Jtgc2CMkXucA0tmycXSAwOFU4kmBZ3PMnL0fALbvZz4lV7gVM=
cache:
  directories:
  - _build
  - deps
script:
  - mix test
deploy:
- provider: script
  script: >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
    make build TAG=dev &&
    make docker-push TAG=dev
  on:
    branch: develop
  skip_cleanup: true
- provider: script
  script: >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
    make build TAG=latest &&
    make docker-push TAG=latest
  on:
    branch: master
  skip_cleanup: true
notifications:
  webhooks:
    urls:
      - secure: "hDTcJUYpJ5OIpAQLfLkUkoaqd35JR5hNoyZKTVynL/ulHY5/gqJVqZJBPxb9mP2Tun/8bBE0QyhDWm2Bj/vghbhDKM1k+ZBpJBrSKwRPmDBUaaId8IsDbjTvpbkuDBTVJrhieP1xx3tQMV1FJBydvuGtr74qvDshcevgjy/OcriOJyTcbsVAmm9+VYgFI/i/Wki9F0actxE85966x5ctAZXeGUCHKDley6Rf6icxJlIwI2KvlpSqGgREvHhvUYukkT93WxT367rZOJtkT3uzNLEUJhFvtLCYW2RXi6rxGh33GJYl6CebbBliOU/37nr7yEYX0wj/gPDWJ7GOeDKVN88G2vhtSH+Zk9tCpGmkzEAmglcEnpc24BI8w8OtZl0jMm3Ahv+VERWUpGRMTK9u+4iRGD3G8mswDJXAlVnXKPhkxH4mhsjZtzhbAXhV+xDVWiox/bhS3KWFf8FuCh0jetsWYd9noYNpVQGjtM9jI328uqWN+PEBWdGbDRwIzIlPGnKtLhqZuhOv0JkkB10orHrPvQII6ywYZHpOMclGggVKdSp7WOvh56WQJNmzUvkL1jrgy2MoRFb1jz4EaThstMpAczzbxNXorVWxNZHviy1ExDQGqZ/ene7zaD04C7rCnP2GoaWuKMiMf+cliVE6iawrocWI395LKiIiGM/YuAA="
    on_failure: always
    on_success: change
