version: '3'
services:
  nats:
    image: 'nats:linux'
    container_name: nats.local
    expose:
      - "4222"
    ports:
      - "4222:4222"
    networks:
     - net1
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
  testchain-deployment:
    image: makerdao/testchain-deployment:dev
    container_name: testchain-deployment.local
    ports:
      - "5001:5001"
    environment:
      TCD_GATEWAY: host=host.docker.internal
      GITHUB_DEFAULT_CHECKOUT_TARGET: tags/staxx-deploy
    volumes:
      - nix-db:/nix
    tmpfs:
      - /tmp
    depends_on:
      - nats
    networks:
     - net1

# We're using custom network setup, as it ships with a DNS
# system which allows containers to communicate by hostnames.
networks:
  net1:
    driver: bridge

volumes:
  nix-db:
